version: "3.9"
services:
  terraform:
    image: hashicorp/terraform
    volumes:
      - .:/infra
    working_dir: /infra
    environment: 
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}