name: down

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container: yifanfu/docker-essentials:latest

    steps:
      - uses: actions/checkout@v2

      - name: Terraform init
        run: |
          make init
      
      - name: Terraform destroy
        run: |
          make destroy
